# Site settings
title: joj.log(code)
subtitle: 
email: busy.joj@gmail.com
description: Slow and steady win the game.
baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://busy-joj.github.io/" # the base hostname & protocol for your site
author: 
github_address: https://github.com/busy-joj
city: Republic of Korea
state: 
zip_code:
country:
phone:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
